name: Build for Windows

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Release tag."
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        ref: ${{ github.event.inputs.version || github.ref }}

    - name: Set up uv
      uses: astral-sh/setup-uv@v10.2.0
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install 3.14

    - name: Install dependencies
      run: uv sync --extra build

    - name: Build with PyInstaller
      shell: pwsh
      env:
        RAW_VERSION: ${{ github.event.release.tag_name || github.event.inputs.version }}
      run: |
        $repoName = "{{ github.repository }}".Split("/")[1]
        $rawVersion = $env:RAW_VERSION
        $version = $rawVersion -replace '^[vV]', ''
        
        uv run pyinstaller `
          --onefile `
          --noconsole `
          src/rulescrafter/__init__.py `
          --name "${repoName}-${version}-windows-x86_64" `
          --add-data "src/rulescrafter/gui/icons;rulescrafter/gui/icons"

    - name: Upload release asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.release.tag_name || github.event.inputs.version }}
        files: dist/*-windows-x86_64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
